-- Brightness control (0.0 to 2.0, where 1.0 is normal)
local brightness = 0.9

-- Helper function to adjust color brightness
local function adjust_brightness(hex, factor)
  local r = tonumber(hex:sub(2, 3), 16)
  local g = tonumber(hex:sub(4, 5), 16)
  local b = tonumber(hex:sub(6, 7), 16)

  r = math.min(255, math.floor(r * factor))
  g = math.min(255, math.floor(g * factor))
  b = math.min(255, math.floor(b * factor))

  return string.format("#%02x%02x%02x", r, g, b)
end

local base_colors
local ok, shared_colors = pcall(dofile, os.getenv("HOME") .. "/.colors.lua")
if ok then
  base_colors = shared_colors
else
  base_colors = {
    bg = "#2F2F2F",
    fg = "#E6E6E6",
    blue = "#8aadf4",
    green = "#a6da95",
    yellow = "#eed49f",
    red = "#ed8796",
    purple = "#f5bde6",
    orange = "#8bd5ca",
    comment = "#a0845c",
    selection = "#373b41",
    line = "#2a2a2a",
    gray1 = "#2a2a2a",
    gray2 = "#373737",
    gray3 = "#4a4a4a",
    gray4 = "#5b6078",
    subtle_red = "#2a1f1f",
    none = "NONE",
  }
end

-- Apply brightness to colors (only main syntax colors)
local c = {}
local syntax_colors = { "blue", "green", "yellow", "red", "purple", "orange" }
for key, value in pairs(base_colors) do
  local is_syntax_color = false
  for _, color in ipairs(syntax_colors) do
    if key == color then
      is_syntax_color = true
      break
    end
  end

  if is_syntax_color then
    c[key] = adjust_brightness(value, brightness)
  else
    c[key] = value
  end
end

-- Old colorset (commented out)

-- New colorset (Catppuccin-inspired)
-- local c = {
--   bg = "#24292e",
--   fg = "#cad3f5",
--   blue = "#8aadf4",
--   green = "#a6da95",
--   yellow = "#eed49f",
--   red = "#ed8796",
--   purple = "#f5bde6",
--   orange = "#f5a97f",
--   comment = "#6e738d",
--   selection = "#f4dbd6",
--   line = "#363d46",
--   gray1 = "#494d64",
--   gray2 = "#5b6078",
--   gray3 = "#6e738d",
--   gray4 = "#8087a2",
--   none = "NONE",
-- }

vim.g.colors_name = "custom-theme"
vim.cmd("highlight clear")

local hl = vim.api.nvim_set_hl
function highlight(color, opts)
  hl(0, color, opts)
end

-- Editor
highlight("Normal", { fg = c.fg, bg = c.bg })
highlight("NormalFloat", { fg = c.fg, bg = c.gray1 })
highlight("NormalNC", { fg = c.fg, bg = c.bg })
highlight("NormalSB", { fg = c.fg, bg = c.gray1 })
highlight("Comment", { fg = c.comment, italic = true })
highlight("LineNr", { fg = c.gray4 })
highlight("CursorLine", { bg = c.line })
highlight("CursorLineNr", { fg = c.fg, bg = c.line })
highlight("CursorColumn", { bg = c.line })
highlight("ColorColumn", { bg = c.gray1 })
highlight("Visual", { bg = c.selection })
highlight("VisualNOS", { bg = c.selection })
highlight("Search", { bg = c.yellow, fg = c.bg })
highlight("IncSearch", { bg = c.orange, fg = c.bg })
highlight("CurSearch", { bg = c.red, fg = c.bg })
highlight("Substitute", { bg = c.red, fg = c.bg })
highlight("StatusLine", { fg = c.fg, bg = c.gray2 })
highlight("StatusLineNC", { fg = c.gray1, bg = c.gray2 })
highlight("TabLine", { fg = c.gray3, bg = c.gray1 })
highlight("TabLineFill", { bg = c.gray1 })
highlight("TabLineSel", { fg = c.fg, bg = c.bg })
highlight("WinSeparator", { fg = c.gray3 })
highlight("VertSplit", { fg = c.gray3 })
highlight("Pmenu", { fg = c.fg, bg = c.gray1 })
highlight("PmenuSel", { fg = c.bg, bg = c.blue })
highlight("PmenuSbar", { bg = c.gray2 })
highlight("PmenuThumb", { bg = c.gray3 })
highlight("FloatBorder", { fg = c.gray3, bg = c.gray1 })
highlight("FloatTitle", { fg = c.fg, bg = c.gray1 })
highlight("FloatShadow", { fg = c.gray3 })
highlight("Directory", { fg = c.blue })
highlight("ErrorMsg", { fg = c.red, bold = true })
highlight("WarningMsg", { fg = c.yellow })
highlight("ModeMsg", { fg = c.fg, bold = true })
highlight("MoreMsg", { fg = c.blue })
highlight("MsgArea", { fg = c.fg })
highlight("MsgSeparator", { fg = c.gray3 })
highlight("Question", { fg = c.blue })
highlight("QuickFixLine", { bg = c.gray2, bold = true })
highlight("MatchParen", { fg = c.orange, bold = true })
highlight("Conceal", { fg = c.gray3 })
highlight("Cursor", { fg = c.bg, bg = c.fg })
highlight("lCursor", { fg = c.bg, bg = c.fg })
highlight("CursorIM", { fg = c.bg, bg = c.fg })
highlight("TermCursor", { fg = c.bg, bg = c.fg })
highlight("TermCursorNC", { fg = c.bg, bg = c.gray3 })
highlight("Title", { fg = c.blue, bold = true })
highlight("Folded", { fg = c.blue, bg = c.gray1 })
highlight("FoldColumn", { fg = c.gray3 })
highlight("SignColumn", { fg = c.gray3 })
highlight("SignColumnSB", { fg = c.gray3, bg = c.gray1 })
highlight("NonText", { fg = c.gray3 })
highlight("SpecialKey", { fg = c.gray3 })
highlight("Whitespace", { fg = c.gray2 })
highlight("EndOfBuffer", { fg = c.bg })
highlight("WildMenu", { fg = c.bg, bg = c.blue })
highlight("WinBar", { fg = c.fg })
highlight("WinBarNC", { fg = c.gray3 })

-- Diff
highlight("DiffAdd", { bg = c.green, fg = c.bg })
highlight("DiffChange", { bg = c.yellow, fg = c.bg })
highlight("DiffDelete", { bg = c.red, fg = c.bg })
highlight("DiffText", { bg = c.blue, fg = c.bg })
highlight("diffAdded", { fg = c.green })
highlight("diffRemoved", { fg = c.red })
highlight("diffChanged", { fg = c.blue })
highlight("diffOldFile", { fg = c.yellow })
highlight("diffNewFile", { fg = c.orange })
highlight("diffFile", { fg = c.blue })
highlight("diffLine", { fg = c.gray3 })
highlight("diffIndexLine", { fg = c.blue })

-- Syntax
highlight("String", { fg = c.green })
highlight("Character", { fg = c.green })
highlight("Number", { fg = c.orange })
highlight("Float", { fg = c.orange })
highlight("Boolean", { fg = c.orange })
highlight("Function", { fg = c.blue })
highlight("Keyword", { fg = c.purple })
highlight("Type", { fg = c.yellow })
highlight("Typedef", { fg = c.yellow })
highlight("StorageClass", { fg = c.yellow })
highlight("Structure", { fg = c.yellow })
highlight("Constant", { fg = c.orange })
highlight("Identifier", { fg = c.fg })
highlight("Operator", { fg = c.fg })
highlight("PreProc", { fg = c.purple })
highlight("Include", { fg = c.purple })
highlight("Define", { fg = c.purple })
highlight("Macro", { fg = c.blue })
highlight("PreCondit", { fg = c.purple })
highlight("Special", { fg = c.orange })
highlight("SpecialChar", { fg = c.orange })
highlight("SpecialComment", { fg = c.comment })
highlight("Statement", { fg = c.purple })
highlight("Conditional", { fg = c.purple })
highlight("Repeat", { fg = c.purple })
highlight("Label", { fg = c.blue })
highlight("Exception", { fg = c.red })
highlight("Tag", { fg = c.blue })
highlight("Delimiter", { fg = c.fg })
highlight("Debug", { fg = c.red })
highlight("Underlined", { underline = true })
highlight("Bold", { bold = true })
highlight("Italic", { italic = true })
highlight("Error", { fg = c.red })
highlight("Todo", { fg = c.bg, bg = c.yellow })

-- TreeSitter
highlight("@variable", { fg = c.fg })
highlight("@variable.builtin", { fg = c.red })
highlight("@variable.parameter", { fg = c.fg })
highlight("@variable.member", { fg = c.blue })
highlight("@constant", { fg = c.orange })
highlight("@constant.builtin", { fg = c.orange })
highlight("@constant.macro", { fg = c.orange })
highlight("@module", { fg = c.blue })
highlight("@string", { fg = c.green })
highlight("@string.escape", { fg = c.orange })
highlight("@string.regexp", { fg = c.green })
highlight("@string.documentation", { fg = c.comment })
highlight("@string.docstring", { fg = c.comment })
highlight("@character", { fg = c.green })
highlight("@character.special", { fg = c.orange })
highlight("@number", { fg = c.orange })
highlight("@number.float", { fg = c.orange })
highlight("@boolean", { fg = c.orange })
highlight("@function", { fg = c.fg })
highlight("@function.builtin", { fg = c.fg })
highlight("@function.call", { fg = c.fg })
highlight("@function.macro", { fg = c.fg })
highlight("@function.method", { fg = c.fg })
highlight("@function.method.call", { fg = c.fg })
highlight("@constructor", { fg = c.blue })
highlight("@operator", { fg = c.fg })
highlight("@keyword", { fg = c.blue })
highlight("@keyword.function", { fg = c.blue })
highlight("@keyword.operator", { fg = c.purple })
highlight("@keyword.import", { fg = c.purple })
highlight("@keyword.type", { fg = c.blue })
highlight("@keyword.modifier", { fg = c.blue })
highlight("@keyword.repeat", { fg = c.purple })
highlight("@keyword.return", { fg = c.purple })
highlight("@keyword.debug", { fg = c.red })
highlight("@keyword.exception", { fg = c.red })
highlight("@keyword.conditional", { fg = c.purple })
highlight("@keyword.conditional.ternary", { fg = c.purple })
highlight("@keyword.directive", { fg = c.purple })
highlight("@keyword.directive.define", { fg = c.purple })
highlight("@type", { fg = c.fg })
highlight("@type.builtin", { fg = c.fg })
highlight("@type.definition", { fg = c.fg })
highlight("@attribute", { fg = c.fg })
highlight("@decorator", { fg = c.blue })
highlight("@decorator.python", { fg = c.blue })
highlight("@function.decorator", { fg = c.blue })
highlight("@variable.member.python", { fg = c.fg })
highlight("@variable.builtin.python", { fg = c.blue })
highlight("@variable.parameter.decorator", { fg = c.blue })
highlight("@identifier.decorator", { fg = c.blue })
highlight("@property", { fg = c.fg })
highlight("@label", { fg = c.blue })
highlight("@namespace", { fg = c.blue })
highlight("@tag", { fg = c.blue })
highlight("@tag.attribute", { fg = c.fg })
highlight("@tag.delimiter", { fg = c.fg })
highlight("@markup.strong", { bold = true })
highlight("@markup.italic", { italic = true })
highlight("@markup.strikethrough", { strikethrough = true })
highlight("@markup.underline", { underline = true })
highlight("@markup.heading", { fg = c.blue, bold = true })
highlight("@markup.quote", { fg = c.comment })
highlight("@markup.math", { fg = c.blue })
highlight("@markup.link", { fg = c.blue, underline = true })
highlight("@markup.link.label", { fg = c.blue })
highlight("@markup.link.url", { fg = c.blue, underline = true })
highlight("@markup.raw", { fg = c.green })
highlight("@markup.raw.block", { fg = c.green })
highlight("@markup.list", { fg = c.blue })
highlight("@markup.list.checked", { fg = c.green })
highlight("@markup.list.unchecked", { fg = c.gray3 })
highlight("@diff.plus", { fg = c.green })
highlight("@diff.minus", { fg = c.red })
highlight("@diff.delta", { fg = c.blue })

-- LSP
highlight("DiagnosticError", { fg = c.red })
highlight("DiagnosticWarn", { fg = c.yellow })
highlight("DiagnosticInfo", { fg = c.blue })
highlight("DiagnosticHint", { fg = c.comment })
highlight("DiagnosticOk", { fg = c.green })
highlight("DiagnosticUnnecessary", { fg = c.yellow })
highlight("DiagnosticVirtualTextError", { fg = c.red })
highlight("DiagnosticVirtualTextWarn", { fg = c.yellow })
highlight("DiagnosticVirtualTextInfo", { fg = c.blue })
highlight("DiagnosticVirtualTextHint", { fg = c.comment })
highlight("DiagnosticVirtualTextOk", { fg = c.green })
highlight("DiagnosticVirtualTextUnnecessary", { fg = c.yellow })
highlight("DiagnosticUnderlineError", {})
highlight("DiagnosticUnderlineWarn", {})
highlight("DiagnosticUnderlineInfo", {})
highlight("DiagnosticUnderlineHint", {})
highlight("DiagnosticUnderlineOk", {})
highlight("DiagnosticUnderlineUnnecessary", {})
highlight("LspReferenceText", { bg = c.gray2 })
highlight("LspReferenceRead", { bg = c.gray2 })
highlight("LspReferenceWrite", { bg = c.gray2 })
highlight("LspCodeLens", { fg = c.comment })
highlight("LspCodeLensSeparator", { fg = c.comment })
highlight("LspSignatureActiveParameter", { bg = c.gray2, bold = true })

-- Completion
highlight("CmpItemAbbr", { fg = c.fg })
highlight("CmpItemAbbrDeprecated", { fg = c.gray3, strikethrough = true })
highlight("CmpItemAbbrMatch", { fg = c.blue, bold = true })
highlight("CmpItemAbbrMatchFuzzy", { fg = c.blue, bold = true })
highlight("CmpItemKind", { fg = c.purple })
highlight("CmpItemMenu", { fg = c.comment })
highlight("BlinkCmpMenu", { fg = c.fg, bg = c.gray1 })
highlight("BlinkCmpMenuBorder", { fg = c.gray3, bg = c.gray1 })
highlight("BlinkCmpMenuSelection", { fg = c.bg, bg = c.blue })
highlight("BlinkCmpLabel", { fg = c.fg })
highlight("BlinkCmpLabelMatch", { fg = c.blue, bold = true })
highlight("BlinkCmpKind", { fg = c.purple })

-- Git
highlight("GitSignsAdd", { fg = c.green })
highlight("GitSignsChange", { fg = c.yellow })
highlight("GitSignsDelete", { fg = c.red })
highlight("GitSignsAddNr", { fg = c.green })
highlight("GitSignsChangeNr", { fg = c.yellow })
highlight("GitSignsDeleteNr", { fg = c.red })
highlight("GitSignsAddLn", { bg = c.green, fg = c.bg })
highlight("GitSignsChangeLn", { bg = c.yellow, fg = c.bg })
highlight("GitSignsDeleteLn", { bg = c.red, fg = c.bg })
highlight("GitSignsCurrentLineBlame", { fg = c.comment })

-- Telescope
highlight("TelescopeNormal", { fg = c.fg, bg = c.gray1 })
highlight("TelescopeBorder", { fg = c.gray3, bg = c.gray1 })
highlight("TelescopeTitle", { fg = c.fg, bg = c.gray1 })
highlight("TelescopeSelection", { bg = c.gray2 })
highlight("TelescopeSelectionCaret", { fg = c.blue })
highlight("TelescopeMultiSelection", { fg = c.purple })
highlight("TelescopeMatching", { fg = c.blue, bold = true })
highlight("TelescopePromptNormal", { fg = c.fg, bg = c.gray1 })
highlight("TelescopePromptBorder", { fg = c.gray3, bg = c.gray1 })
highlight("TelescopePromptTitle", { fg = c.fg, bg = c.gray1 })
highlight("TelescopePromptPrefix", { fg = c.blue })
highlight("TelescopeResultsNormal", { fg = c.fg, bg = c.gray1 })
highlight("TelescopeResultsBorder", { fg = c.gray3, bg = c.gray1 })
highlight("TelescopeResultsTitle", { fg = c.fg, bg = c.gray1 })
highlight("TelescopePreviewNormal", { fg = c.fg, bg = c.gray1 })
highlight("TelescopePreviewBorder", { fg = c.gray3, bg = c.gray1 })
highlight("TelescopePreviewTitle", { fg = c.fg, bg = c.gray1 })

-- FzfLua
highlight("FzfLuaNormal", { fg = c.fg, bg = c.bg })
highlight("FzfLuaBorder", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaTitle", { fg = c.fg, bg = c.gray2, bold = true })
highlight("FzfLuaTitleFlags", { fg = c.comment })
highlight("FzfLuaCursor", { fg = c.bg, bg = c.blue })
highlight("FzfLuaCursorLine", { bg = c.line })
highlight("FzfLuaSearch", { fg = c.blue, bold = true })
highlight("FzfLuaScrollBorderEmpty", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaScrollBorderFull", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaScrollFloatEmpty", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaScrollFloatFull", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaHelpNormal", { fg = c.fg, bg = c.bg })
highlight("FzfLuaHelpBorder", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaPreviewNormal", { fg = c.fg, bg = c.bg })
highlight("FzfLuaPreviewBorder", { fg = c.gray3, bg = c.bg })
highlight("FzfLuaPreviewTitle", { fg = c.fg, bg = c.gray2, bold = true })
highlight("FzfLuaBackdrop", { fg = c.gray3 })
highlight("FzfLuaLivePrompt", { fg = c.red })

-- Telescope (match FzfLua colors)
highlight("TelescopeNormal", { fg = c.fg, bg = c.bg })
highlight("TelescopeBorder", { fg = c.bg, bg = c.bg })
highlight("TelescopePromptBorder", { fg = c.bg, bg = c.bg })
highlight("TelescopeResultsBorder", { fg = c.bg, bg = c.bg })
highlight("TelescopePreviewBorder", { fg = c.bg, bg = c.bg })
highlight("TelescopeSelection", { bg = c.line })
highlight("TelescopeMatching", { fg = c.red, bold = true })
highlight("TelescopePromptNormal", { fg = c.fg, bg = c.bg })
highlight("TelescopeResultsNormal", { fg = c.fg, bg = c.bg })
highlight("TelescopePreviewNormal", { fg = c.fg, bg = c.bg })

-- Which-key
highlight("WhichKey", { fg = c.blue })
highlight("WhichKeyGroup", { fg = c.purple })
highlight("WhichKeyDesc", { fg = c.fg })
highlight("WhichKeySeperator", { fg = c.comment })
highlight("WhichKeySeparator", { fg = c.comment })
highlight("WhichKeyFloat", { bg = c.gray1 })
highlight("WhichKeyValue", { fg = c.comment })

-- Flash
highlight("FlashBackdrop", { fg = c.gray3 })
highlight("FlashMatch", { fg = c.bg, bg = c.blue })
highlight("FlashCurrent", { fg = c.bg, bg = c.orange })
highlight("FlashLabel", { fg = c.bg, bg = c.red, bold = true })

-- Oil
highlight("OilDir", { fg = c.blue })
highlight("OilDirIcon", { fg = c.blue })
highlight("OilLink", { fg = c.purple })
highlight("OilLinkTarget", { fg = c.green })
highlight("OilCopy", { fg = c.yellow, bold = true })
highlight("OilMove", { fg = c.purple, bold = true })
highlight("OilChange", { fg = c.orange, bold = true })
highlight("OilCreate", { fg = c.green, bold = true })
highlight("OilDelete", { fg = c.red, bold = true })

-- Indent
highlight("IblIndent", { fg = c.gray2 })
highlight("IblScope", { fg = c.gray3 })
highlight("IndentBlanklineChar", { fg = c.gray2 })
highlight("IndentBlanklineContextChar", { fg = c.gray3 })

-- Trouble
highlight("TroubleText", { fg = c.fg })
highlight("TroubleCount", { fg = c.purple, bg = c.gray2 })
highlight("TroubleNormal", { fg = c.fg, bg = c.gray1 })

-- Notify
highlight("NotifyERRORBorder", { fg = c.red })
highlight("NotifyWARNBorder", { fg = c.yellow })
highlight("NotifyINFOBorder", { fg = c.blue })
highlight("NotifyDEBUGBorder", { fg = c.comment })
highlight("NotifyTRACEBorder", { fg = c.purple })
highlight("NotifyERRORIcon", { fg = c.red })
highlight("NotifyWARNIcon", { fg = c.yellow })
highlight("NotifyINFOIcon", { fg = c.blue })
highlight("NotifyDEBUGIcon", { fg = c.comment })
highlight("NotifyTRACEIcon", { fg = c.purple })

-- Lualine
highlight("lualine_a_normal", { fg = c.fg, bg = c.gray1 })
highlight("lualine_b_normal", { fg = c.fg, bg = c.gray1 })
highlight("lualine_c_normal", { fg = c.fg, bg = c.gray1 })
highlight("lualine_a_insert", { fg = c.fg, bg = c.gray1 })
highlight("lualine_b_insert", { fg = c.fg, bg = c.gray1 })
highlight("lualine_c_insert", { fg = c.fg, bg = c.gray1 })
highlight("lualine_a_visual", { fg = c.fg, bg = c.gray1 })
highlight("lualine_b_visual", { fg = c.fg, bg = c.gray1 })
highlight("lualine_c_visual", { fg = c.fg, bg = c.gray1 })
highlight("lualine_a_command", { fg = c.fg, bg = c.gray1 })
highlight("lualine_b_command", { fg = c.fg, bg = c.gray1 })
highlight("lualine_c_command", { fg = c.fg, bg = c.gray1 })
highlight("lualine_a_replace", { fg = c.fg, bg = c.gray1 })
highlight("lualine_b_replace", { fg = c.fg, bg = c.gray1 })
highlight("lualine_c_replace", { fg = c.fg, bg = c.gray1 })
highlight("lualine_a_inactive", { fg = c.comment, bg = c.gray1 })
highlight("lualine_b_inactive", { fg = c.comment, bg = c.gray1 })
highlight("lualine_c_inactive", { fg = c.comment, bg = c.gray1 })

-- Mason
highlight("MasonHeader", { fg = c.bg, bg = c.blue, bold = true })
highlight("MasonHeaderSecondary", { fg = c.bg, bg = c.purple, bold = true })
highlight("MasonHighlight", { fg = c.blue })
highlight("MasonHighlightBlock", { fg = c.bg, bg = c.blue })
highlight("MasonHighlightBlockBold", { fg = c.bg, bg = c.blue, bold = true })
highlight("MasonHighlightSecondary", { fg = c.purple })
highlight("MasonHighlightBlockSecondary", { fg = c.bg, bg = c.purple })
highlight("MasonHighlightBlockBoldSecondary", { fg = c.bg, bg = c.purple, bold = true })
highlight("MasonMuted", { fg = c.comment })
highlight("MasonMutedBlock", { fg = c.fg, bg = c.gray1 })
highlight("MasonMutedBlockBold", { fg = c.fg, bg = c.gray1, bold = true })

-- DAP
highlight("DapBreakpoint", { fg = c.red })
highlight("DapBreakpointCondition", { fg = c.yellow })
highlight("DapBreakpointRejected", { fg = c.comment })
highlight("DapLogPoint", { fg = c.blue })
highlight("DapStopped", { fg = c.green })

-- Grapple
highlight("GrappleHint", { fg = c.comment })
highlight("GrappleName", { fg = c.blue })
highlight("GrappleCurrent", { fg = c.orange, bold = true })

-- Yanky
highlight("YankyPut", { fg = c.bg, bg = c.orange })
highlight("YankyYanked", { fg = c.bg, bg = c.blue })

-- Mini
highlight("MiniAnimateCursor", { reverse = true })
highlight("MiniAnimateNormalFloat", { fg = c.fg, bg = c.gray1 })
highlight("MiniClueBorder", { fg = c.gray3, bg = c.gray1 })
highlight("MiniClueDescGroup", { fg = c.purple })
highlight("MiniClueDescSingle", { fg = c.fg })
highlight("MiniClueNextKey", { fg = c.blue })
highlight("MiniClueNextKeyWithPostkeys", { fg = c.comment })
highlight("MiniClueSeparator", { fg = c.comment })
highlight("MiniClueTitle", { fg = c.fg, bold = true })
highlight("MiniCompletionActiveParameter", { underline = true })
highlight("MiniCursorword", { bg = c.gray2 })
highlight("MiniCursorwordCurrent", { bg = c.gray2 })
highlight("MiniDepsChangeAdded", { fg = c.green })
highlight("MiniDepsChangeRemoved", { fg = c.red })
highlight("MiniDepsHint", { fg = c.comment })
highlight("MiniDepsInfo", { fg = c.blue })
highlight("MiniDepsMsgBreaking", { fg = c.red })
highlight("MiniDepsPlaceholder", { fg = c.comment })
highlight("MiniDepsTitle", { fg = c.fg, bold = true })
highlight("MiniDepsTitleError", { fg = c.red, bold = true })
highlight("MiniDepsTitleSame", { fg = c.comment, bold = true })
highlight("MiniDepsTitleUpdate", { fg = c.green, bold = true })
highlight("MiniDiffSignAdd", { fg = c.green })
highlight("MiniDiffSignChange", { fg = c.yellow })
highlight("MiniDiffSignDelete", { fg = c.red })
highlight("MiniFilesBorder", { fg = c.gray3, bg = c.gray1 })
highlight("MiniFilesBorderModified", { fg = c.yellow, bg = c.gray1 })
highlight("MiniFilesCursorLine", { bg = c.gray2 })
highlight("MiniFilesDirectory", { fg = c.blue })
highlight("MiniFilesFile", { fg = c.fg })
highlight("MiniFilesNormal", { fg = c.fg, bg = c.gray1 })
highlight("MiniFilesTitle", { fg = c.fg, bg = c.gray1 })
highlight("MiniFilesTitleFocused", { fg = c.fg, bg = c.gray1, bold = true })
highlight("MiniHipatternsFixme", { fg = c.bg, bg = c.red, bold = true })
highlight("MiniHipatternsHack", { fg = c.bg, bg = c.yellow, bold = true })
highlight("MiniHipatternsNote", { fg = c.bg, bg = c.blue, bold = true })
highlight("MiniHipatternsTodo", { fg = c.bg, bg = c.purple, bold = true })
highlight("MiniIconsAzure", { fg = c.blue })
highlight("MiniIconsBlue", { fg = c.blue })
highlight("MiniIconsCyan", { fg = c.blue })
highlight("MiniIconsGreen", { fg = c.green })
highlight("MiniIconsGrey", { fg = c.gray3 })
highlight("MiniIconsOrange", { fg = c.orange })
highlight("MiniIconsPurple", { fg = c.purple })
highlight("MiniIconsRed", { fg = c.red })
highlight("MiniIconsYellow", { fg = c.yellow })
highlight("MiniIndentscopeSymbol", { fg = c.gray3 })
highlight("MiniJump", { fg = c.bg, bg = c.purple })
highlight("MiniJump2dSpot", { fg = c.bg, bg = c.red, bold = true })
highlight("MiniJump2dSpotAhead", { fg = c.bg, bg = c.blue, bold = true })
highlight("MiniJump2dSpotUnique", { fg = c.bg, bg = c.orange, bold = true })
highlight("MiniMapNormal", { fg = c.fg, bg = c.gray1 })
highlight("MiniMapSymbolCount", { fg = c.purple })
highlight("MiniMapSymbolLine", { fg = c.blue })
highlight("MiniMapSymbolView", { fg = c.blue })
highlight("MiniNotifyBorder", { fg = c.gray3, bg = c.gray1 })
highlight("MiniNotifyNormal", { fg = c.fg, bg = c.gray1 })
highlight("MiniNotifyTitle", { fg = c.fg, bg = c.gray1 })
highlight("MiniOperatorsExchangeFrom", { fg = c.bg, bg = c.red })
highlight("MiniPickBorder", { fg = c.gray3, bg = c.gray1 })
highlight("MiniPickBorderBusy", { fg = c.yellow, bg = c.gray1 })
highlight("MiniPickBorderText", { fg = c.blue, bg = c.gray1 })
highlight("MiniPickIconDirectory", { fg = c.blue })
highlight("MiniPickIconFile", { fg = c.fg })
highlight("MiniPickMatchCurrent", { bg = c.gray2 })
highlight("MiniPickMatchMarked", { fg = c.purple })
highlight("MiniPickMatchRanges", { fg = c.blue, bold = true })
highlight("MiniPickNormal", { fg = c.fg, bg = c.gray1 })
highlight("MiniPickPreviewLine", { bg = c.gray2 })
highlight("MiniPickPreviewRegion", { bg = c.selection })
highlight("MiniPickPrompt", { fg = c.blue, bg = c.gray1 })
highlight("MiniStarterCurrent", { bg = c.gray2 })
highlight("MiniStarterFooter", { fg = c.comment, italic = true })
highlight("MiniStarterHeader", { fg = c.blue })
highlight("MiniStarterInactive", { fg = c.comment })
highlight("MiniStarterItem", { fg = c.fg })
highlight("MiniStarterItemBullet", { fg = c.gray3 })
highlight("MiniStarterItemPrefix", { fg = c.yellow })
highlight("MiniStarterQuery", { fg = c.blue })
highlight("MiniStarterSection", { fg = c.purple })
highlight("MiniStatuslineDevinfo", { fg = c.fg, bg = c.gray2 })
highlight("MiniStatuslineFileinfo", { fg = c.fg, bg = c.gray2 })
highlight("MiniStatuslineFilename", { fg = c.fg, bg = c.gray1 })
highlight("MiniStatuslineInactive", { fg = c.gray3, bg = c.gray1 })
highlight("MiniStatuslineModeCommand", { fg = c.bg, bg = c.yellow, bold = true })
highlight("MiniStatuslineModeInsert", { fg = c.bg, bg = c.green, bold = true })
highlight("MiniStatuslineModeNormal", { fg = c.bg, bg = c.blue, bold = true })
highlight("MiniStatuslineModeOther", { fg = c.bg, bg = c.purple, bold = true })
highlight("MiniStatuslineModeReplace", { fg = c.bg, bg = c.red, bold = true })
highlight("MiniStatuslineModeVisual", { fg = c.bg, bg = c.orange, bold = true })
highlight("MiniSurround", { fg = c.bg, bg = c.orange })
highlight("MiniTablineCurrent", { fg = c.fg, bg = c.bg })
highlight("MiniTablineFill", { bg = c.gray1 })
highlight("MiniTablineHidden", { fg = c.gray3, bg = c.gray1 })
highlight("MiniTablineModifiedCurrent", { fg = c.yellow, bg = c.bg })
highlight("MiniTablineModifiedHidden", { fg = c.yellow, bg = c.gray1 })
highlight("MiniTablineModifiedVisible", { fg = c.yellow, bg = c.gray2 })
highlight("MiniTablineTabpagesection", { fg = c.bg, bg = c.blue, bold = true })
highlight("MiniTablineVisible", { fg = c.fg, bg = c.gray2 })
highlight("MiniTestEmphasis", { bold = true })
highlight("MiniTestFail", { fg = c.red, bold = true })
highlight("MiniTestPass", { fg = c.green, bold = true })
highlight("MiniTrailspace", { bg = c.red })

-- Spell
highlight("SpellBad", { sp = c.red, undercurl = true })
highlight("SpellCap", { sp = c.yellow, undercurl = true })
highlight("SpellLocal", { sp = c.blue, undercurl = true })
highlight("SpellRare", { sp = c.purple, undercurl = true })

-- Health
highlight("healthError", { fg = c.red })
highlight("healthSuccess", { fg = c.green })
highlight("healthWarning", { fg = c.yellow })

-- Markdown
highlight("markdownHeadingDelimiter", { fg = c.orange, bold = true })
highlight("markdownCode", { fg = c.green })
highlight("markdownCodeBlock", { fg = c.green })
highlight("markdownLinkText", { fg = c.blue, underline = true })
highlight("markdownH1", { fg = c.blue, bold = true })
highlight("markdownH2", { fg = c.purple, bold = true })
highlight("markdownH3", { fg = c.green, bold = true })
highlight("markdownH4", { fg = c.yellow, bold = true })
highlight("markdownH5", { fg = c.orange, bold = true })
highlight("markdownH6", { fg = c.red, bold = true })

-- HTML
highlight("htmlTag", { fg = c.blue })
highlight("htmlEndTag", { fg = c.blue })
highlight("htmlTagName", { fg = c.purple })
highlight("htmlArg", { fg = c.yellow })
highlight("htmlSpecialChar", { fg = c.orange })

-- CSS
highlight("cssBraces", { fg = c.fg })
highlight("cssClassName", { fg = c.yellow })
highlight("cssClassNameDot", { fg = c.yellow })
highlight("cssProp", { fg = c.blue })
highlight("cssAttr", { fg = c.orange })

-- JavaScript
highlight("javaScriptFunction", { fg = c.purple })
highlight("javaScriptRootObject", { fg = c.blue })
highlight("javaScriptIdentifier", { fg = c.purple })
highlight("javaScriptOperator", { fg = c.purple })

-- Python
highlight("pythonOperator", { fg = c.purple })
highlight("pythonRepeat", { fg = c.purple })
highlight("pythonInclude", { fg = c.purple })
highlight("pythonStatement", { fg = c.purple })

-- Java
highlight("javaOperator", { fg = c.purple })
highlight("javaClassDecl", { fg = c.yellow })

-- Go
highlight("goDirective", { fg = c.purple })
highlight("goConstants", { fg = c.orange })
highlight("goDeclaration", { fg = c.purple })
highlight("goDeclType", { fg = c.blue })
highlight("goBuiltins", { fg = c.orange })

-- YAML
highlight("yamlKey", { fg = c.blue })
highlight("yamlAnchor", { fg = c.purple })
highlight("yamlAlias", { fg = c.green })
highlight("yamlDocumentHeader", { fg = c.purple })

-- JSON
highlight("jsonKeyword", { fg = c.blue })
highlight("jsonQuote", { fg = c.gray3 })
highlight("jsonBraces", { fg = c.fg })
highlight("jsonString", { fg = c.green })

-- XML
highlight("xmlTag", { fg = c.blue })
highlight("xmlEndTag", { fg = c.blue })
highlight("xmlTagName", { fg = c.purple })
highlight("xmlEqual", { fg = c.orange })
highlight("xmlAttrib", { fg = c.yellow })
highlight("xmlAttribPunct", { fg = c.orange })
highlight("xmlString", { fg = c.green })

-- SQL
highlight("sqlKeyword", { fg = c.purple })
highlight("sqlFunction", { fg = c.blue })
highlight("sqlOperator", { fg = c.purple })

-- Dockerfile
highlight("dockerfileKeyword", { fg = c.purple })

-- Vim
highlight("vimCommand", { fg = c.purple })
highlight("vimLet", { fg = c.purple })
highlight("vimFuncKey", { fg = c.purple })
highlight("vimFunction", { fg = c.blue })
highlight("vimIsCommand", { fg = c.fg })

-- Lua
highlight("luaIn", { fg = c.purple })
highlight("luaFunction", { fg = c.purple })
highlight("luaTable", { fg = c.fg })

-- DevIcons
highlight("DevIconLua", { fg = c.blue })
highlight("DevIconPy", { fg = c.yellow })
highlight("DevIconJs", { fg = c.yellow })
highlight("DevIconTs", { fg = c.blue })
highlight("DevIconJava", { fg = c.red })
highlight("DevIconGo", { fg = c.blue })
highlight("DevIconRs", { fg = c.orange })
highlight("DevIconC", { fg = c.blue })
highlight("DevIconCpp", { fg = c.blue })
highlight("DevIconCs", { fg = c.purple })
highlight("DevIconPhp", { fg = c.purple })
highlight("DevIconRb", { fg = c.red })
highlight("DevIconSwift", { fg = c.orange })
highlight("DevIconKt", { fg = c.purple })
highlight("DevIconScala", { fg = c.red })
highlight("DevIconHtml", { fg = c.orange })
highlight("DevIconCss", { fg = c.blue })
highlight("DevIconSass", { fg = c.purple })
highlight("DevIconLess", { fg = c.blue })
highlight("DevIconJson", { fg = c.yellow })
highlight("DevIconXml", { fg = c.orange })
highlight("DevIconYml", { fg = c.purple })
highlight("DevIconYaml", { fg = c.purple })
highlight("DevIconToml", { fg = c.orange })
highlight("DevIconIni", { fg = c.gray3 })
highlight("DevIconConf", { fg = c.gray3 })
highlight("DevIconConfig", { fg = c.gray3 })
highlight("DevIconEnv", { fg = c.yellow })
highlight("DevIconDockerfile", { fg = c.blue })
highlight("DevIconMd", { fg = c.blue })
highlight("DevIconTxt", { fg = c.fg })
highlight("DevIconLog", { fg = c.gray3 })
highlight("DevIconSql", { fg = c.orange })
highlight("DevIconDb", { fg = c.orange })
highlight("DevIconSh", { fg = c.green })
highlight("DevIconBash", { fg = c.green })
highlight("DevIconZsh", { fg = c.green })
highlight("DevIconFish", { fg = c.green })
highlight("DevIconVim", { fg = c.green })
highlight("DevIconGitignore", { fg = c.red })
highlight("DevIconGitconfig", { fg = c.red })
highlight("DevIconLicense", { fg = c.yellow })
highlight("DevIconReadme", { fg = c.blue })
highlight("DevIconMakefile", { fg = c.orange })
highlight("DevIconCMakeLists", { fg = c.gray3 })
highlight("DevIconPackageJson", { fg = c.green })
highlight("DevIconPackageLockJson", { fg = c.red })
highlight("DevIconNodeModules", { fg = c.red })
highlight("DevIconNpm", { fg = c.red })
highlight("DevIconYarn", { fg = c.blue })
highlight("DevIconWebpack", { fg = c.blue })
highlight("DevIconGulp", { fg = c.red })
highlight("DevIconGrunt", { fg = c.orange })
highlight("DevIconBower", { fg = c.orange })
highlight("DevIconGemfile", { fg = c.red })
highlight("DevIconCargoToml", { fg = c.orange })
highlight("DevIconPomXml", { fg = c.orange })
highlight("DevIconGradleBuild", { fg = c.blue })
highlight("DevIconSbt", { fg = c.red })
highlight("DevIconRequirementsTxt", { fg = c.blue })
highlight("DevIconPipfile", { fg = c.blue })
highlight("DevIconGoMod", { fg = c.blue })
highlight("DevIconGoSum", { fg = c.blue })
highlight("DevIconComposerJson", { fg = c.purple })
highlight("DevIconComposerLock", { fg = c.purple })
highlight("DevIconGemspec", { fg = c.red })
highlight("DevIconRakefile", { fg = c.red })
highlight("DevIconProcfile", { fg = c.purple })
highlight("DevIconHeroku", { fg = c.purple })
highlight("DevIconNetlify", { fg = c.blue })
highlight("DevIconVercel", { fg = c.fg })
highlight("DevIconAws", { fg = c.orange })
highlight("DevIconGcp", { fg = c.blue })
highlight("DevIconAzure", { fg = c.blue })
highlight("DevIconTerraform", { fg = c.purple })
highlight("DevIconKubernetes", { fg = c.blue })
highlight("DevIconHelm", { fg = c.blue })
highlight("DevIconAnsible", { fg = c.red })
highlight("DevIconVagrant", { fg = c.blue })
highlight("DevIconDefault", { fg = c.fg })
highlight("DevIconFolder", { fg = c.blue })
highlight("DevIconFolderOpen", { fg = c.blue })
highlight("DevIconSymlink", { fg = c.purple })
highlight("DevIconExe", { fg = c.red })
highlight("DevIconBin", { fg = c.red })
highlight("DevIconDll", { fg = c.red })
highlight("DevIconSo", { fg = c.red })
highlight("DevIconDylib", { fg = c.red })
highlight("DevIconA", { fg = c.red })
highlight("DevIconO", { fg = c.red })
highlight("DevIconZip", { fg = c.yellow })
highlight("DevIconTar", { fg = c.yellow })
highlight("DevIconGz", { fg = c.yellow })
highlight("DevIconRar", { fg = c.yellow })
highlight("DevIcon7z", { fg = c.yellow })
highlight("DevIconPdf", { fg = c.red })
highlight("DevIconDoc", { fg = c.blue })
highlight("DevIconDocx", { fg = c.blue })
highlight("DevIconXls", { fg = c.green })
highlight("DevIconXlsx", { fg = c.green })
highlight("DevIconPpt", { fg = c.orange })
highlight("DevIconPptx", { fg = c.orange })
highlight("DevIconJpg", { fg = c.purple })
highlight("DevIconJpeg", { fg = c.purple })
highlight("DevIconPng", { fg = c.purple })
highlight("DevIconGif", { fg = c.purple })
highlight("DevIconSvg", { fg = c.orange })
highlight("DevIconIco", { fg = c.yellow })
highlight("DevIconBmp", { fg = c.purple })
highlight("DevIconTiff", { fg = c.purple })
highlight("DevIconWebp", { fg = c.purple })
highlight("DevIconMp3", { fg = c.red })
highlight("DevIconMp4", { fg = c.red })
highlight("DevIconAvi", { fg = c.red })
highlight("DevIconMov", { fg = c.red })
highlight("DevIconWav", { fg = c.red })
highlight("DevIconFlac", { fg = c.red })
highlight("DevIconOgg", { fg = c.red })
highlight("DevIconFont", { fg = c.fg })
highlight("DevIconTtf", { fg = c.fg })
highlight("DevIconOtf", { fg = c.fg })
highlight("DevIconWoff", { fg = c.fg })
highlight("DevIconWoff2", { fg = c.fg })
highlight("DevIconEot", { fg = c.fg })

-- Additional DevIcons
highlight("DevIcon3DObjectFile", { fg = c.purple })
highlight("DevIcon3gp", { fg = c.red })
highlight("DevIconAOSC", { fg = c.blue })
highlight("DevIconAPL", { fg = c.yellow })
highlight("DevIconASM", { fg = c.red })
highlight("DevIconAUTHORS", { fg = c.yellow })
highlight("DevIconAdaBody", { fg = c.blue })
highlight("DevIconAdaFile", { fg = c.blue })
highlight("DevIconAdaSpecification", { fg = c.blue })
highlight("DevIconAdvancedAudioCoding", { fg = c.red })
highlight("DevIconAi", { fg = c.orange })
highlight("DevIconAlmalinux", { fg = c.blue })
highlight("DevIconAlpine", { fg = c.blue })
highlight("DevIconAndroid", { fg = c.green })
highlight("DevIconApp", { fg = c.blue })
highlight("DevIconApple", { fg = c.fg })
highlight("DevIconAppleScript", { fg = c.blue })
highlight("DevIconArch", { fg = c.blue })
highlight("DevIconArchcraft", { fg = c.blue })
highlight("DevIconArchlabs", { fg = c.blue })
highlight("DevIconArcoLinux", { fg = c.blue })
highlight("DevIconArduino", { fg = c.blue })
highlight("DevIconArtix", { fg = c.blue })
highlight("DevIconAsc", { fg = c.gray3 })
highlight("DevIconAsciinema", { fg = c.red })
highlight("DevIconAss", { fg = c.yellow })
highlight("DevIconAstro", { fg = c.orange })
highlight("DevIconAudioInterchangeFileFormat", { fg = c.red })
highlight("DevIconAutoCADDwg", { fg = c.blue })
highlight("DevIconAutoCADDxf", { fg = c.blue })
highlight("DevIconAvif", { fg = c.purple })
highlight("DevIconAwk", { fg = c.green })
highlight("DevIconAzureCli", { fg = c.blue })
highlight("DevIconBSPWM", { fg = c.gray3 })
highlight("DevIconBabelrc", { fg = c.yellow })
highlight("DevIconBackup", { fg = c.gray3 })
highlight("DevIconBashProfile", { fg = c.green })
highlight("DevIconBashrc", { fg = c.green })
highlight("DevIconBat", { fg = c.green })
highlight("DevIconBazel", { fg = c.green })
highlight("DevIconBazelBuild", { fg = c.green })
highlight("DevIconBazelWorkspace", { fg = c.green })
highlight("DevIconBibTeX", { fg = c.blue })
highlight("DevIconBicep", { fg = c.blue })
highlight("DevIconBicepParameters", { fg = c.blue })
highlight("DevIconBigLinux", { fg = c.blue })
highlight("DevIconBinaryGLTF", { fg = c.purple })
highlight("DevIconBlade", { fg = c.red })
highlight("DevIconBlender", { fg = c.orange })
highlight("DevIconBlueprint", { fg = c.blue })
highlight("DevIconBoundaryRepresentation", { fg = c.purple })
highlight("DevIconBrewfile", { fg = c.orange })
highlight("DevIconBudgie", { fg = c.blue })
highlight("DevIconBuildProps", { fg = c.orange })
highlight("DevIconBuildTargets", { fg = c.orange })
highlight("DevIconBunLockfile", { fg = c.yellow })
highlight("DevIconBz", { fg = c.yellow })
highlight("DevIconBz2", { fg = c.yellow })
highlight("DevIconBz3", { fg = c.yellow })
highlight("DevIconBzl", { fg = c.green })
highlight("DevIconCMake", { fg = c.gray3 })
highlight("DevIconCPlusPlus", { fg = c.blue })
highlight("DevIconCPlusPlusModule", { fg = c.blue })
highlight("DevIconCSharpProject", { fg = c.purple })
highlight("DevIconCache", { fg = c.gray3 })
highlight("DevIconCantorrc", { fg = c.blue })
highlight("DevIconCentos", { fg = c.purple })
highlight("DevIconCheckhealth", { fg = c.green })
highlight("DevIconCinnamon", { fg = c.orange })
highlight("DevIconCjs", { fg = c.yellow })
highlight("DevIconClangConfig", { fg = c.blue })
highlight("DevIconClojure", { fg = c.blue })
highlight("DevIconClojureC", { fg = c.blue })
highlight("DevIconClojureDart", { fg = c.blue })
highlight("DevIconClojureJS", { fg = c.blue })
highlight("DevIconCobol", { fg = c.blue })
highlight("DevIconCodeOfConduct", { fg = c.yellow })
highlight("DevIconCodespell", { fg = c.gray3 })
highlight("DevIconCoffee", { fg = c.orange })
highlight("DevIconColdFusionScript", { fg = c.blue })
highlight("DevIconColdFusionTag", { fg = c.blue })
highlight("DevIconCommitlintConfig", { fg = c.yellow })
highlight("DevIconConda", { fg = c.green })
highlight("DevIconConfigRu", { fg = c.red })
highlight("DevIconConfiguration", { fg = c.gray3 })
highlight("DevIconCowsayFile", { fg = c.yellow })
highlight("DevIconCp", { fg = c.blue })
highlight("DevIconCppm", { fg = c.blue })
highlight("DevIconCrdownload", { fg = c.gray3 })
highlight("DevIconCrystal", { fg = c.fg })
highlight("DevIconCrystalLinux", { fg = c.purple })
highlight("DevIconCsh", { fg = c.green })
highlight("DevIconCson", { fg = c.yellow })
highlight("DevIconCsv", { fg = c.green })
highlight("DevIconCts", { fg = c.blue })
highlight("DevIconCue", { fg = c.purple })
highlight("DevIconCxx", { fg = c.blue })
highlight("DevIconCxxm", { fg = c.blue })
highlight("DevIconD", { fg = c.red })
highlight("DevIconDart", { fg = c.blue })
highlight("DevIconDconf", { fg = c.gray3 })
highlight("DevIconDebian", { fg = c.red })
highlight("DevIconDeepin", { fg = c.blue })
highlight("DevIconDesktopEntry", { fg = c.gray3 })
highlight("DevIconDevuan", { fg = c.purple })
highlight("DevIconDiff", { fg = c.gray3 })
highlight("DevIconDockerIgnore", { fg = c.blue })
highlight("DevIconDot", { fg = c.blue })
highlight("DevIconDownload", { fg = c.gray3 })
highlight("DevIconDrools", { fg = c.red })
highlight("DevIconDropbox", { fg = c.blue })
highlight("DevIconDsStore", { fg = c.gray3 })
highlight("DevIconDump", { fg = c.gray3 })
highlight("DevIconEbook", { fg = c.orange })
highlight("DevIconEditorConfig", { fg = c.gray3 })
highlight("DevIconEdn", { fg = c.blue })
highlight("DevIconEex", { fg = c.purple })
highlight("DevIconEjs", { fg = c.yellow })
highlight("DevIconElementary", { fg = c.blue })
highlight("DevIconElf", { fg = c.red })
highlight("DevIconElisp", { fg = c.purple })
highlight("DevIconElm", { fg = c.blue })
highlight("DevIconEmbeddedOpenTypeFont", { fg = c.fg })
highlight("DevIconEndeavour", { fg = c.purple })
highlight("DevIconEnlightenment", { fg = c.blue })
highlight("DevIconEpp", { fg = c.orange })
highlight("DevIconEpub", { fg = c.orange })
highlight("DevIconErb", { fg = c.red })
highlight("DevIconErl", { fg = c.red })
highlight("DevIconEslintIgnore", { fg = c.purple })
highlight("DevIconEslintrc", { fg = c.purple })
highlight("DevIconEx", { fg = c.purple })
highlight("DevIconExs", { fg = c.purple })
highlight("DevIconFIGletFontControl", { fg = c.fg })
highlight("DevIconFIGletFontFormat", { fg = c.fg })
highlight("DevIconFavicon", { fg = c.yellow })
highlight("DevIconFdmdownload", { fg = c.gray3 })
highlight("DevIconFeature", { fg = c.green })
highlight("DevIconFedora", { fg = c.blue })
highlight("DevIconFennel", { fg = c.yellow })
highlight("DevIconFluxbox", { fg = c.gray3 })
highlight("DevIconFortran", { fg = c.purple })
highlight("DevIconFragmentShader", { fg = c.red })
highlight("DevIconFreeBSD", { fg = c.red })
highlight("DevIconFreeCAD", { fg = c.red })
highlight("DevIconFreeCADConfig", { fg = c.red })
highlight("DevIconFreeLosslessAudioCodec", { fg = c.red })
highlight("DevIconFs", { fg = c.blue })
highlight("DevIconFsharp", { fg = c.blue })
highlight("DevIconFsi", { fg = c.blue })
highlight("DevIconFsscript", { fg = c.blue })
highlight("DevIconFsx", { fg = c.blue })
highlight("DevIconFusion360", { fg = c.orange })
highlight("DevIconGCode", { fg = c.blue })
highlight("DevIconGDScript", { fg = c.blue })
highlight("DevIconGIMP", { fg = c.purple })
highlight("DevIconGNOME", { fg = c.blue })
highlight("DevIconGPRBuildProject", { fg = c.orange })
highlight("DevIconGTK", { fg = c.blue })
highlight("DevIconGarudaLinux", { fg = c.blue })
highlight("DevIconGentoo", { fg = c.purple })
highlight("DevIconGentooBuild", { fg = c.purple })
highlight("DevIconGeometryShader", { fg = c.green })
highlight("DevIconGitAttributes", { fg = c.red })
highlight("DevIconGitBlameIgnore", { fg = c.red })
highlight("DevIconGitCommit", { fg = c.red })
highlight("DevIconGitLogo", { fg = c.red })
highlight("DevIconGitModules", { fg = c.red })
highlight("DevIconGitlabCI", { fg = c.orange })
highlight("DevIconGleam", { fg = c.purple })
highlight("DevIconGoWork", { fg = c.blue })
highlight("DevIconGodotProject", { fg = c.blue })
highlight("DevIconGodotTextResource", { fg = c.blue })
highlight("DevIconGodotTextScene", { fg = c.blue })
highlight("DevIconGradle", { fg = c.blue })
highlight("DevIconGradleBuildScript", { fg = c.blue })
highlight("DevIconGradleProperties", { fg = c.blue })
highlight("DevIconGradleSettings", { fg = c.blue })
highlight("DevIconGradleWrapperProperties", { fg = c.blue })
highlight("DevIconGradleWrapperScript", { fg = c.blue })
highlight("DevIconGraphQL", { fg = c.purple })
highlight("DevIconGroovy", { fg = c.blue })
highlight("DevIconGruntfile", { fg = c.orange })
highlight("DevIconGuix", { fg = c.yellow })
highlight("DevIconGulpfile", { fg = c.red })
highlight("DevIconGv", { fg = c.blue })
highlight("DevIconGvimrc", { fg = c.green })
highlight("DevIconH", { fg = c.blue })
highlight("DevIconHTTP", { fg = c.blue })
highlight("DevIconHaml", { fg = c.red })
highlight("DevIconHaxe", { fg = c.orange })
highlight("DevIconHbs", { fg = c.orange })
highlight("DevIconHeex", { fg = c.purple })
highlight("DevIconHexadecimal", { fg = c.gray3 })
highlight("DevIconHh", { fg = c.blue })
highlight("DevIconHpp", { fg = c.blue })
highlight("DevIconHrl", { fg = c.red })
highlight("DevIconHs", { fg = c.purple })
highlight("DevIconHtm", { fg = c.orange })
highlight("DevIconHuff", { fg = c.blue })
highlight("DevIconHurl", { fg = c.orange })
highlight("DevIconHxx", { fg = c.blue })
highlight("DevIconHyperbolaGNULinuxLibre", { fg = c.gray3 })
highlight("DevIconHypridle", { fg = c.blue })
highlight("DevIconHyprland", { fg = c.blue })
highlight("DevIconHyprlandd", { fg = c.blue })
highlight("DevIconHyprlock", { fg = c.blue })
highlight("DevIconHyprpaper", { fg = c.blue })
highlight("DevIconHyprsunset", { fg = c.blue })
highlight("DevIconI18nConfig", { fg = c.gray3 })
highlight("DevIconIcal", { fg = c.blue })
highlight("DevIconIcalendar", { fg = c.blue })
highlight("DevIconIcs", { fg = c.blue })
highlight("DevIconIfb", { fg = c.blue })
highlight("DevIconIfc", { fg = c.purple })
highlight("DevIconIge", { fg = c.purple })
highlight("DevIconIges", { fg = c.purple })
highlight("DevIconIgs", { fg = c.purple })
highlight("DevIconIllumos", { fg = c.orange })
highlight("DevIconImage", { fg = c.purple })
highlight("DevIconImg", { fg = c.purple })
highlight("DevIconImportConfiguration", { fg = c.gray3 })
highlight("DevIconIndexTheme", { fg = c.gray3 })
highlight("DevIconInfo", { fg = c.blue })
highlight("DevIconIonic", { fg = c.blue })
highlight("DevIconIso", { fg = c.yellow })
highlight("DevIconIxx", { fg = c.blue })
highlight("DevIconJWM", { fg = c.blue })
highlight("DevIconJar", { fg = c.red })
highlight("DevIconJavaScriptReactSpec", { fg = c.yellow })
highlight("DevIconJavaScriptReactTest", { fg = c.yellow })
highlight("DevIconJenkins", { fg = c.blue })
highlight("DevIconJl", { fg = c.purple })
highlight("DevIconJpegXl", { fg = c.purple })
highlight("DevIconJson5", { fg = c.yellow })
highlight("DevIconJsonc", { fg = c.yellow })
highlight("DevIconJsx", { fg = c.blue })
highlight("DevIconJustfile", { fg = c.gray3 })
highlight("DevIconKDEPlasma", { fg = c.blue })
highlight("DevIconKDEglobals", { fg = c.blue })
highlight("DevIconKDEneon", { fg = c.green })
highlight("DevIconKalgebrarc", { fg = c.blue })
highlight("DevIconKali", { fg = c.blue })
highlight("DevIconKbx", { fg = c.gray3 })
highlight("DevIconKdb", { fg = c.gray3 })
highlight("DevIconKdbx", { fg = c.gray3 })
highlight("DevIconKdenlive", { fg = c.blue })
highlight("DevIconKdenliveLayoutsrc", { fg = c.blue })
highlight("DevIconKdenliverc", { fg = c.blue })
highlight("DevIconKiCad", { fg = c.blue })
highlight("DevIconKiCadCache", { fg = c.blue })
highlight("DevIconKiCadFootprintTable", { fg = c.blue })
highlight("DevIconKiCadSymbolTable", { fg = c.blue })
highlight("DevIconKotlin", { fg = c.purple })
highlight("DevIconKotlinScript", { fg = c.purple })
highlight("DevIconKrita", { fg = c.purple })
highlight("DevIconKritadisplayrc", { fg = c.purple })
highlight("DevIconKritarc", { fg = c.purple })
highlight("DevIconKsh", { fg = c.green })
highlight("DevIconKubuntu", { fg = c.blue })
highlight("DevIconLXDE", { fg = c.gray3 })
highlight("DevIconLXDEConfigFile", { fg = c.gray3 })
highlight("DevIconLXLE", { fg = c.blue })
highlight("DevIconLXQt", { fg = c.blue })
highlight("DevIconLXQtConfigFile", { fg = c.blue })
highlight("DevIconLabView", { fg = c.yellow })
highlight("DevIconLeap", { fg = c.green })
highlight("DevIconLeex", { fg = c.purple })
highlight("DevIconLhs", { fg = c.purple })
highlight("DevIconLib", { fg = c.red })
highlight("DevIconLibreOfficeCalc", { fg = c.green })
highlight("DevIconLibreOfficeFormula", { fg = c.blue })
highlight("DevIconLibreOfficeGraphics", { fg = c.orange })
highlight("DevIconLibreOfficeImpress", { fg = c.orange })
highlight("DevIconLibreOfficeWriter", { fg = c.blue })
highlight("DevIconLibrecadFontFile", { fg = c.fg })
highlight("DevIconLinux", { fg = c.yellow })
highlight("DevIconLinuxKernelObject", { fg = c.yellow })
highlight("DevIconLiquid", { fg = c.green })
highlight("DevIconLocOS", { fg = c.blue })
highlight("DevIconLocalization", { fg = c.blue })
highlight("DevIconLock", { fg = c.red })
highlight("DevIconLogos", { fg = c.fg })
highlight("DevIconLrc", { fg = c.yellow })
highlight("DevIconLuau", { fg = c.blue })
highlight("DevIconLuaurc", { fg = c.blue })
highlight("DevIconM3u", { fg = c.red })
highlight("DevIconM3u8", { fg = c.red })
highlight("DevIconM4V", { fg = c.red })
highlight("DevIconMATE", { fg = c.green })
highlight("DevIconMPEG4", { fg = c.red })
highlight("DevIconMPEGAudioLayerIII", { fg = c.red })
highlight("DevIconMXLinux", { fg = c.fg })
highlight("DevIconMageia", { fg = c.blue })
highlight("DevIconMagnet", { fg = c.red })
highlight("DevIconMailmap", { fg = c.red })
highlight("DevIconManjaro", { fg = c.green })
highlight("DevIconMarkdown", { fg = c.blue })
highlight("DevIconMaterial", { fg = c.red })
highlight("DevIconMaven", { fg = c.orange })
highlight("DevIconMd5", { fg = c.gray3 })
highlight("DevIconMdx", { fg = c.blue })
highlight("DevIconMint", { fg = c.green })
highlight("DevIconMixLock", { fg = c.purple })
highlight("DevIconMjs", { fg = c.yellow })
highlight("DevIconMkv", { fg = c.red })
highlight("DevIconMl", { fg = c.orange })
highlight("DevIconMli", { fg = c.orange })
highlight("DevIconMobi", { fg = c.orange })
highlight("DevIconMojo", { fg = c.orange })
highlight("DevIconMonkeysAudio", { fg = c.red })
highlight("DevIconMotoko", { fg = c.yellow })
highlight("DevIconMpp", { fg = c.blue })
highlight("DevIconMpv", { fg = c.red })
highlight("DevIconMts", { fg = c.red })
highlight("DevIconMustache", { fg = c.orange })
highlight("DevIconNPMIgnore", { fg = c.red })
highlight("DevIconNPMrc", { fg = c.red })
highlight("DevIconNano", { fg = c.blue })
highlight("DevIconNextConfigCjs", { fg = c.fg })
highlight("DevIconNextConfigJs", { fg = c.fg })
highlight("DevIconNextConfigTs", { fg = c.fg })
highlight("DevIconNfo", { fg = c.gray3 })
highlight("DevIconNim", { fg = c.yellow })
highlight("DevIconNix", { fg = c.blue })
highlight("DevIconNixOS", { fg = c.blue })
highlight("DevIconNobaraLinux", { fg = c.blue })
highlight("DevIconNorg", { fg = c.blue })
highlight("DevIconNotebook", { fg = c.orange })
highlight("DevIconNswag", { fg = c.green })
highlight("DevIconNushell", { fg = c.green })
highlight("DevIconNuxtConfig", { fg = c.green })
highlight("DevIconObjectFile", { fg = c.red })
highlight("DevIconObjectiveC", { fg = c.blue })
highlight("DevIconObjectiveCPlusPlus", { fg = c.blue })
highlight("DevIconOdin", { fg = c.blue })
highlight("DevIconOggMultiplex", { fg = c.red })
highlight("DevIconOggSpeexAudio", { fg = c.red })
highlight("DevIconOggVideo", { fg = c.red })
highlight("DevIconOggVorbis", { fg = c.red })
highlight("DevIconOpenBSD", { fg = c.yellow })
highlight("DevIconOpenGLShadingLanguage", { fg = c.orange })
highlight("DevIconOpenSCAD", { fg = c.yellow })
highlight("DevIconOpenTypeFont", { fg = c.fg })
highlight("DevIconOpusAudioFile", { fg = c.red })
highlight("DevIconOrgMode", { fg = c.green })
highlight("DevIconOut", { fg = c.red })
highlight("DevIconPKGBUILD", { fg = c.blue })
highlight("DevIconPNPMFile", { fg = c.yellow })
highlight("DevIconPNPMLock", { fg = c.yellow })
highlight("DevIconPNPMWorkspace", { fg = c.yellow })
highlight("DevIconPackagesProps", { fg = c.orange })
highlight("DevIconPackedResource", { fg = c.purple })
highlight("DevIconParabolaGNULinuxLibre", { fg = c.purple })
highlight("DevIconParrot", { fg = c.blue })
highlight("DevIconPart", { fg = c.gray3 })
highlight("DevIconPatch", { fg = c.gray3 })
highlight("DevIconPl", { fg = c.blue })
highlight("DevIconPlatformio", { fg = c.orange })
highlight("DevIconPlaywrightConfig", { fg = c.red })
highlight("DevIconPls", { fg = c.red })
highlight("DevIconPm", { fg = c.blue })
highlight("DevIconPop_OS", { fg = c.blue })
highlight("DevIconPp", { fg = c.blue })
highlight("DevIconPreCommitConfig", { fg = c.yellow })
highlight("DevIconPrettierConfig", { fg = c.purple })
highlight("DevIconPrettierIgnore", { fg = c.purple })
highlight("DevIconPrisma", { fg = c.blue })
highlight("DevIconProlog", { fg = c.orange })
highlight("DevIconPrusaSlicer", { fg = c.orange })
highlight("DevIconPsManifestfile", { fg = c.blue })
highlight("DevIconPsScriptModulefile", { fg = c.blue })
highlight("DevIconPsScriptfile", { fg = c.blue })
highlight("DevIconPsb", { fg = c.blue })
highlight("DevIconPsd", { fg = c.blue })
highlight("DevIconPub", { fg = c.blue })
highlight("DevIconPulseCodeModulation", { fg = c.red })
highlight("DevIconPuppyLinux", { fg = c.blue })
highlight("DevIconPxd", { fg = c.yellow })
highlight("DevIconPxi", { fg = c.yellow })
highlight("DevIconPy.typed", { fg = c.yellow })
highlight("DevIconPyLintConfig", { fg = c.yellow })
highlight("DevIconPyc", { fg = c.yellow })
highlight("DevIconPyd", { fg = c.yellow })
highlight("DevIconPyi", { fg = c.yellow })
highlight("DevIconPyo", { fg = c.yellow })
highlight("DevIconPyw", { fg = c.yellow })
highlight("DevIconPyx", { fg = c.yellow })
highlight("DevIconQt", { fg = c.green })
highlight("DevIconQtile", { fg = c.blue })
highlight("DevIconQubesOS", { fg = c.blue })
highlight("DevIconQuery", { fg = c.blue })
highlight("DevIconR", { fg = c.blue })
highlight("DevIconRake", { fg = c.red })
highlight("DevIconRasi", { fg = c.orange })
highlight("DevIconRaspberryPiOS", { fg = c.red })
highlight("DevIconRazorPage", { fg = c.blue })
highlight("DevIconReScript", { fg = c.red })
highlight("DevIconReScriptInterface", { fg = c.red })
highlight("DevIconRedhat", { fg = c.red })
highlight("DevIconRlib", { fg = c.orange })
highlight("DevIconRmd", { fg = c.blue })
highlight("DevIconRobotsTxt", { fg = c.gray3 })
highlight("DevIconRockyLinux", { fg = c.green })
highlight("DevIconRproj", { fg = c.blue })
highlight("DevIconRss", { fg = c.orange })
highlight("DevIconSRCINFO", { fg = c.blue })
highlight("DevIconSabayon", { fg = c.blue })
highlight("DevIconScalaScript", { fg = c.red })
highlight("DevIconScheme", { fg = c.red })
highlight("DevIconScss", { fg = c.purple })
highlight("DevIconSecurity", { fg = c.yellow })
highlight("DevIconSettingsJson", { fg = c.purple })
highlight("DevIconSha1", { fg = c.gray3 })
highlight("DevIconSha224", { fg = c.gray3 })
highlight("DevIconSha256", { fg = c.gray3 })
highlight("DevIconSha384", { fg = c.gray3 })
highlight("DevIconSha512", { fg = c.gray3 })
highlight("DevIconSharedObject", { fg = c.red })
highlight("DevIconSig", { fg = c.gray3 })
highlight("DevIconSignature", { fg = c.gray3 })
highlight("DevIconSketchUp", { fg = c.red })
highlight("DevIconSlackware", { fg = c.blue })
highlight("DevIconSlim", { fg = c.orange })
highlight("DevIconSln", { fg = c.purple })
highlight("DevIconSlnx", { fg = c.purple })
highlight("DevIconSml", { fg = c.orange })
highlight("DevIconSolidWorksAsm", { fg = c.red })
highlight("DevIconSolidWorksPrt", { fg = c.red })
highlight("DevIconSolidity", { fg = c.blue })
highlight("DevIconSolus", { fg = c.blue })
highlight("DevIconSolveSpace", { fg = c.blue })
highlight("DevIconSpecJs", { fg = c.yellow })
highlight("DevIconSpecTs", { fg = c.blue })
highlight("DevIconSrt", { fg = c.yellow })
highlight("DevIconSsa", { fg = c.yellow })
highlight("DevIconStaticLibraryArchive", { fg = c.red })
highlight("DevIconSte", { fg = c.purple })
highlight("DevIconStep", { fg = c.purple })
highlight("DevIconStorybookJavaScript", { fg = c.red })
highlight("DevIconStorybookJsx", { fg = c.red })
highlight("DevIconStorybookMjs", { fg = c.red })
highlight("DevIconStorybookSvelte", { fg = c.red })
highlight("DevIconStorybookTsx", { fg = c.red })
highlight("DevIconStorybookTypeScript", { fg = c.red })
highlight("DevIconStorybookVue", { fg = c.red })
highlight("DevIconStp", { fg = c.purple })
highlight("DevIconStyl", { fg = c.green })
highlight("DevIconSub", { fg = c.yellow })
highlight("DevIconSublime", { fg = c.orange })
highlight("DevIconSuo", { fg = c.purple })
highlight("DevIconSvelte", { fg = c.orange })
highlight("DevIconSvelteConfig", { fg = c.orange })
highlight("DevIconSvgz", { fg = c.orange })
highlight("DevIconSway", { fg = c.blue })
highlight("DevIconSystemVerilog", { fg = c.green })
highlight("DevIconTFVars", { fg = c.purple })
highlight("DevIconTSConfig", { fg = c.blue })
highlight("DevIconTails", { fg = c.purple })
highlight("DevIconTailwindConfig", { fg = c.blue })
highlight("DevIconTcl", { fg = c.blue })
highlight("DevIconTempl", { fg = c.yellow })
highlight("DevIconTemplate", { fg = c.gray3 })
highlight("DevIconTerminal", { fg = c.fg })
highlight("DevIconTestJs", { fg = c.yellow })
highlight("DevIconTestTs", { fg = c.blue })
highlight("DevIconTex", { fg = c.blue })
highlight("DevIconTgz", { fg = c.yellow })
highlight("DevIconThunderbird", { fg = c.blue })
highlight("DevIconTmux", { fg = c.green })
highlight("DevIconTor", { fg = c.purple })
highlight("DevIconTorrent", { fg = c.green })
highlight("DevIconTrisquelGNULinux", { fg = c.blue })
highlight("DevIconTrueTypeFont", { fg = c.fg })
highlight("DevIconTsx", { fg = c.blue })
highlight("DevIconTumbleweed", { fg = c.green })
highlight("DevIconTwig", { fg = c.green })
highlight("DevIconTxz", { fg = c.yellow })
highlight("DevIconTypeScript", { fg = c.blue })
highlight("DevIconTypeScriptDeclaration", { fg = c.blue })
highlight("DevIconTypeScriptReactSpec", { fg = c.blue })
highlight("DevIconTypeScriptReactTest", { fg = c.blue })
highlight("DevIconTypoScript", { fg = c.orange })
highlight("DevIconTypoScriptConfig", { fg = c.orange })
highlight("DevIconTypoScriptSetup", { fg = c.orange })
highlight("DevIconTypst", { fg = c.blue })
highlight("DevIconUI", { fg = c.blue })
highlight("DevIconUbuntu", { fg = c.orange })
highlight("DevIconVHDL", { fg = c.green })
highlight("DevIconVLC", { fg = c.orange })
highlight("DevIconVRML", { fg = c.purple })
highlight("DevIconVagrantfile", { fg = c.blue })
highlight("DevIconVala", { fg = c.purple })
highlight("DevIconVanillaOS", { fg = c.yellow })
highlight("DevIconVerilog", { fg = c.green })
highlight("DevIconVertexShader", { fg = c.green })
highlight("DevIconVimrc", { fg = c.green })
highlight("DevIconViteConfig", { fg = c.yellow })
highlight("DevIconVitestConfig", { fg = c.yellow })
highlight("DevIconVlang", { fg = c.blue })
highlight("DevIconVoid", { fg = c.green })
highlight("DevIconVsix", { fg = c.blue })
highlight("DevIconVue", { fg = c.green })
highlight("DevIconWasm", { fg = c.purple })
highlight("DevIconWavPack", { fg = c.red })
highlight("DevIconWavPackCorrection", { fg = c.red })
highlight("DevIconWaveformAudioFile", { fg = c.red })
highlight("DevIconWebOpenFontFormat", { fg = c.fg })
highlight("DevIconWebm", { fg = c.red })
highlight("DevIconWebmanifest", { fg = c.yellow })
highlight("DevIconWeston", { fg = c.blue })
highlight("DevIconWindows", { fg = c.blue })
highlight("DevIconWindowsMediaAudio", { fg = c.red })
highlight("DevIconWindowsMediaVideo", { fg = c.red })
highlight("DevIconWranglerConfig", { fg = c.orange })
highlight("DevIconXDPH", { fg = c.blue })
highlight("DevIconXInitrc", { fg = c.gray3 })
highlight("DevIconXSettingsdConf", { fg = c.gray3 })
highlight("DevIconXaml", { fg = c.blue })
highlight("DevIconXauthority", { fg = c.gray3 })
highlight("DevIconXcLocalization", { fg = c.blue })
highlight("DevIconXcPlayground", { fg = c.blue })
highlight("DevIconXeroLinux", { fg = c.blue })
highlight("DevIconXfce", { fg = c.blue })
highlight("DevIconXorgConf", { fg = c.gray3 })
highlight("DevIconXpi", { fg = c.orange })
highlight("DevIconXresources", { fg = c.gray3 })
highlight("DevIconXsession", { fg = c.gray3 })
highlight("DevIconXul", { fg = c.orange })
highlight("DevIconXz", { fg = c.yellow })
highlight("DevIconZig", { fg = c.orange })
highlight("DevIconZigObjectNotation", { fg = c.orange })
highlight("DevIconZorin", { fg = c.blue })
highlight("DevIconZshenv", { fg = c.green })
highlight("DevIconZshprofile", { fg = c.green })
highlight("DevIconZshrc", { fg = c.green })
highlight("DevIconZst", { fg = c.yellow })
highlight("DevIconapk", { fg = c.green })
highlight("DevIconawesome", { fg = c.blue })
highlight("DevIconcuda", { fg = c.green })
highlight("DevIconcudah", { fg = c.green })
highlight("DevIcondwm", { fg = c.blue })
highlight("DevIconi3", { fg = c.fg })
highlight("DevIconnode", { fg = c.green })
highlight("DevIconopenSUSE", { fg = c.green })
highlight("DevIconpostmarketOS", { fg = c.green })
highlight("DevIconriver", { fg = c.blue })
highlight("DevIconxmonad", { fg = c.purple })

-- Additional missing highlights
highlight("FloatShadowThrough", { fg = c.gray3 })
highlight("FzfLuaBufFlagAlt", { fg = c.purple })
highlight("FzfLuaBufFlagCur", { fg = c.orange })
highlight("FzfLuaBufNr", { fg = c.comment })
highlight("FzfLuaHeaderBind", { fg = c.blue })
highlight("FzfLuaHeaderText", { fg = c.fg })
highlight("FzfLuaLiveSym", { fg = c.red })
highlight("FzfLuaPathColNr", { fg = c.comment })
highlight("FzfLuaPathLineNr", { fg = c.comment })
highlight("FzfLuaTabMarker", { fg = c.green })
highlight("FzfLuaTabTitle", { fg = c.blue })
highlight("GitSignsStagedAdd", { fg = c.green })
highlight("GitSignsStagedAddCul", { fg = c.green })
highlight("GitSignsStagedAddLn", { bg = c.green, fg = c.bg })
highlight("GitSignsStagedAddNr", { fg = c.green })
highlight("GitSignsStagedChange", { fg = c.yellow })
highlight("GitSignsStagedChangeCul", { fg = c.yellow })
highlight("GitSignsStagedChangeLn", { bg = c.yellow, fg = c.bg })
highlight("GitSignsStagedChangeNr", { fg = c.yellow })
highlight("GitSignsStagedChangedelete", { fg = c.red })
highlight("GitSignsStagedChangedeleteCul", { fg = c.red })
highlight("GitSignsStagedChangedeleteLn", { bg = c.red, fg = c.bg })
highlight("GitSignsStagedChangedeleteNr", { fg = c.red })
highlight("GitSignsStagedDelete", { fg = c.red })
highlight("GitSignsStagedDeleteCul", { fg = c.red })
highlight("GitSignsStagedDeleteNr", { fg = c.red })
highlight("GitSignsStagedTopdelete", { fg = c.red })
highlight("GitSignsStagedTopdeleteCul", { fg = c.red })
highlight("GitSignsStagedTopdeleteLn", { bg = c.red, fg = c.bg })
highlight("GitSignsStagedTopdeleteNr", { fg = c.red })
highlight("GitSignsStagedUntracked", { fg = c.purple })
highlight("GitSignsStagedUntrackedCul", { fg = c.purple })
highlight("GitSignsStagedUntrackedLn", { bg = c.purple, fg = c.bg })
highlight("GitSignsStagedUntrackedNr", { fg = c.purple })
highlight("IndentLine", { fg = c.gray2 })
highlight("IndentLineCurrent", { fg = c.gray3 })
highlight("NvimInternalError", { fg = c.red, bg = c.bg })
highlight("RedrawDebugClear", { fg = c.fg, bg = c.yellow })
highlight("RedrawDebugComposed", { fg = c.fg, bg = c.green })
highlight("RedrawDebugRecompose", { fg = c.fg, bg = c.red })
highlight("Removed", { fg = c.red })
highlight("TrailingWhitespace", { bg = c.red })
highlight("fzf1", { fg = c.red })
highlight("fzf2", { fg = c.orange })
highlight("fzf3", { fg = c.yellow })
highlight("lualine_a_terminal", { fg = c.fg, bg = c.gray1 })
highlight("lualine_b_terminal", { fg = c.fg, bg = c.gray1 })
highlight("lualine_c_terminal", { fg = c.fg, bg = c.gray1 })
highlight("lualine_transparent", { bg = c.none })

-- Colorizer highlights
local colorizer_colors = {
  "1e1e1e", "24292e", "2a2a2a", "363d46", "373737", "373b41", "494d64", "4a4a4a",
  "4c5866", "5b6078", "5f819d", "6e738d", "707880", "8087a2", "85a08a", "8aadf4",
  "c8b9ec", "a6da95", "b5a875", "c5c8c6", "cad3f5", "cc6666", "de935f", "ed8796",
  "eed49f", "f4dbd6", "f5a97f", "f5bde6",
}
for _, color in ipairs(colorizer_colors) do
  highlight("colorizer_mf_" .. color, { fg = "#" .. color })
end

-- Lualine diagnostic and diff highlights
local modes = { "command", "inactive", "insert", "normal", "replace", "terminal", "visual" }
local diagnostics = { "error", "hint", "info", "warn" }
local diffs = { "added", "modified", "removed" }

for _, mode in ipairs(modes) do
  for _, diag in ipairs(diagnostics) do
    highlight("lualine_b_diagnostics_" .. diag .. "_" .. mode, { fg = c.fg, bg = c.gray1 })
  end
  for _, diff in ipairs(diffs) do
    highlight("lualine_b_diff_" .. diff .. "_" .. mode, { fg = c.fg, bg = c.gray1 })
  end
end

-- Lualine transitional highlights
highlight("lualine_transitional_lualine_a_command_to_lualine_b_command", { fg = c.gray1, bg = c.gray1 })
highlight("lualine_transitional_lualine_a_normal_to_lualine_b_normal", { fg = c.gray1, bg = c.gray1 })
highlight("lualine_transitional_lualine_a_normal_to_lualine_c_normal", { fg = c.gray1, bg = c.gray1 })
highlight("lualine_transitional_lualine_b_command_to_lualine_c_command", { fg = c.gray1, bg = c.gray1 })
highlight("lualine_transitional_lualine_b_normal_to_lualine_c_normal", { fg = c.gray1, bg = c.gray1 })

-- Lualine filetype highlights
local filetypes = { "DevIconDefault", "DevIconLua" }
for _, ft in ipairs(filetypes) do
  for _, mode in ipairs(modes) do
    highlight("lualine_x_filetype_" .. ft .. "_" .. mode, { fg = c.fg, bg = c.gray1 })
  end
end

_G.discover_highlights = function()
  local groups = {}
  local output = vim.api.nvim_exec2("highlight", { output = true })
  for line in output.output:gmatch("[^\r\n]+") do
    local group = line:match("^(%S+)")
    if group and not group:match("^%s*$") then
      local hl = vim.api.nvim_get_hl(0, { name = group })
      if next(hl) and (hl.fg or hl.bg) then
        groups[group] = true
      end
    end
  end

  local missing = {}
  for group in pairs(groups) do
    local exists = false
    for line in io.lines(debug.getinfo(1).source:sub(2)) do
      if line:match('"' .. group .. '"') then
        exists = true
        break
      end
    end
    if not exists then
      table.insert(missing, group)
    end
  end

  table.sort(missing)
  local file = vim.fn.stdpath("config") .. "/missing_highlights.txt"
  vim.fn.writefile(missing, file)
  print(string.format("Found %d missing highlights in: %s", #missing, file))
end
-- Export colors for use by other modules
return { colors = c }
