local bufnr = vim.api.nvim_get_current_buf()
vim.keymap.set("n", "<leader>cb", "<cmd>:GoBuild<cr>", { desc = "Go Build", buffer = bufnr })
vim.keymap.set("n", "<leader>ta", "<cmd>:GoAddTest<cr>", { desc = "Add Tests", buffer = bufnr })
vim.keymap.set("n", "<leader>tr", "<cmd>:GoTest -n<cr>", { desc = "Test Nearest", buffer = bufnr })
vim.keymap.set("n", "<leader>tf", "<cmd>:GoTestFunc<cr>", { desc = "Run Tests for current Func", buffer = bufnr })
vim.keymap.set("n", "<leader>tF", "<cmd>:GoTestFile<cr>", { desc = "Run Tests for Current File", buffer = bufnr })
vim.keymap.set("n", "<leader>tt", "<cmd>:GoTest -f<cr>", { desc = "Test File", buffer = bufnr })
vim.keymap.set("n", "<leader>tT", "<cmd>:GoTest<cr>", { desc = "Test All", buffer = bufnr })
vim.keymap.set("n", "<leader>tw", "<cmd>:GoTestSum -w<cr>", { desc = "Test Watch Mode", buffer = bufnr })
