-- rosewater = "#f4dbd6",
-- flamingo = "#f0c6c6",
-- pink = "#f5bde6",
-- mauve = "#c6a0f6",
-- red = "#ed8796",
-- maroon = "#ee99a0",
-- peach = "#f5a97f",
-- yellow = "#eed49f",
-- green = "#a6da95",
-- teal = "#8bd5ca",
-- sky = "#91d7e3",
-- sapphire = "#7dc4e4",
-- blue = "#8aadf4",
-- lavender = "#b7bdf8",
-- text = "#cad3f5",
-- subtext1 = "#b8c0e0",
-- subtext0 = "#a5adcb",
-- overlay2 = "#939ab7",
-- overlay1 = "#8087a2",
-- overlay0 = "#6e738d",
-- surface2 = "#5b6078",
-- surface1 = "#494d64",
-- surface0 = "#363a4f",
-- base = "#24273a",
-- mantle = "#1e2030",
-- crust = "#181926",

return {
  "catppuccin/nvim",
  enabled = true,
  name = "catppuccin",
  priority = 1000,
  config = function()
    require("catppuccin").setup({
      term_colors = true,
      highlight_overrides = {
        macchiato = function(colors)
          return {
            LineNr = { fg = colors.text },
            CursorLineNr = { fg = colors.text },
            -- Syntax
            Constant = { fg = colors.blue },
            String = { fg = colors.text },
            ["@variable.parameter"] = { fg = colors.text },
            ["@property"] = { fg = colors.blue },
            Variable = { fg = colors.text },
            Character = { fg = colors.subtext0 },
            Number = { fg = colors.blue },
            Boolean = { fg = colors.blue },
            Float = { fg = colors.blue },
            Identifier = { fg = colors.green },
            Function = { fg = colors.green },
            Statement = { fg = colors.green },
            Conditional = { fg = colors.green },
            Comment = { fg = colors.peach },
            Repeat = { fg = colors.green },
            Label = { fg = colors.green },
            Operator = { fg = colors.subtext0 },
            Keyword = { fg = colors.green },
            Exception = { fg = colors.green },
            PreProc = { fg = colors.yellow },
            Include = { fg = colors.yellow },
            Define = { fg = colors.yellow },
            Macro = { fg = colors.yellow },
            PreCondit = { fg = colors.yellow },
            Type = { fg = colors.blue },
            StorageClass = { fg = colors.overlay2 },
            Structure = { fg = colors.subtext0 },
            Special = { fg = colors.overlay2 },
            SpecialChar = { fg = colors.overlay2 },
            -- FZF
            FzfLuaNormal = { bg = colors.base },
            FzfLuaBorder = { fg = colors.base, bg = colors.base },
            FzfluaTitle = { fg = colors.text, bg = colors.overlay0, style = { "bold" } },
            FzfLuaTitleFlags = { fg = colors.text },
            FzfLuaBackdrop = { bg = colors.surface0 },
            FzfLuaPreviewNormal = { bg = colors.surface0 },
            FzfLuaPreviewBorder = { fg = colors.surface0, bg = colors.surface0 },
            FzfLuaPreviewTitle = { fg = colors.text, bg = colors.overlay0, style = { "bold" } },
            FzfLuaScrollBorderEmpty = { fg = colors.surface0, bg = colors.surface0 },
            FzfLuaScrollBorderFull = { fg = colors.subtext1, bg = colors.surface0 },
            FzfLuaScrollFloatEmpty = { fg = colors.surface0, bg = colors.surface0 },
            FzfLuaScrollFloatFull = { fg = colors.subtext1, bg = colors.surface0 },
            FzfLuaCursorLine = { bg = colors.surface2 },
            FzfLuaLivePrompt = { fg = colors.red },
          }
        end,
      },
    })
    vim.cmd("colorscheme catppuccin-macchiato")
  end,
}

