return {
  { "akinsho/bufferline.nvim", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "lukas-reineke/indent-blankline.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  { "nvim-lualine/lualine.nvim", enabled = false },
  { "nvim-pack/nvim-spectre", enabled = false },
  {
    "nvim-telescope/telescope.nvim",
    keys = {
      { "<leader>/", false },
      { '<leader>s"', false },
      { "<leader>gc", false },
      { "<leader>sa", false },
      { "<leader>sb", false },
      { "<leader>sc", false },
      { "<leader>sC", false },
      { "<leader>sg", false },
      { "<leader>sG", false },
      { "<leader>sh", false },
      { "<leader>sH", false },
      { "<leader>sk", false },
      { "<leader>sm", false },
      { "<leader>sM", false },
      { "<leader>so", false },
      { "<leader>sR", false },
      { "<leader>st", false },
      { "<leader>sT", false },
      { "<leader>sw", false },
      { "<leader>sW", false },
    },
  },
  {
    "folke/todo-comments.nvim",
    keys = {
      { "<leader>st", false },
      { "<leader>sT", false },
    },
  },
}
