return {
  "m4xshen/hardtime.nvim",
  dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
  opts = {
    disabled_filetypes = {
      "DressingSelect",
      "Jaq",
      "Markdown",
      "NeogitStatus",
      "OverseerList",
      "PlenaryTestPopup",
      "TelescopePrompt",
      "checkhealth",
      "dap-repl",
      "dapui_scopes",
      "fugitive",
      "fugitiveblame",
      "fzf",
      "git",
      "harpoon",
      "help",
      "lazy",
      "lspinfo",
      "man",
      "mason",
      "neo-tree",
      "neotest-output",
      "neotest-output-panel",
      "neotest-summary",
      "netrw",
      "notify",
      "oil",
      "qf",
      "spectre_panel",
      "startuptime",
      "tsplayground",
      "blame",
    },
    disable_mouse = false,
  },
}
