return {}
-- return {
--   "karb94/neoscroll.nvim",
--   config = function()
--     require("neoscroll").setup({
--       -- All these keys will be mapped to their corresponding default scrolling animation
--       mappings = { "<C-u>", "<C-d>", "zt", "zz", "zb" },
--       hide_cursor = true, -- Hide cursor while scrolling
--       stop_eof = true, -- Stop at <EOF> when scrolling downwards
--       respect_scrolloff = true, -- Stop scrolling when the cursor reaches the scrolloff margin of the file
--       cursor_scrolls_alone = true, -- The cursor will keep on scrolling even if the window cannot scroll further
--       easing_function = nil, -- quadratic, cubic, quartic, quintic, circular, sine
--       pre_hook = function(info)
--         if info == "cursorline" then
--           vim.wo.cursorline = false
--         end
--       end,
--       post_hook = function(info)
--         if info == "cursorline" then
--           vim.wo.cursorline = true
--         end
--       end,
--       performance_mode = false, -- Disable "Performance Mode" on all buffers.
--     })
--
--     local t = {}
--     t["<C-u>"] = { "scroll", { "-vim.wo.scroll", "true", "350", "sine", [['cursorline']] } }
--     t["<C-d>"] = { "scroll", { "vim.wo.scroll", "true", "350", "sine", [['cursorline']] } }
--     require("neoscroll.config").set_mappings(t)
--   end,
-- }
