-- hi("CmpItemAbbrMatch", { guibg = "none", guifg = "#61afef" })
-- hi("CmpItemAbbrMatchFuzzy", { guibg = "none", guifg = "#61afef" })
-- hi("CmpItemKindFunction", { guibg = "none", guifg = "#c678dd" })
-- hi("CmpItemKindMethod", { guibg = "none", guifg = "#c678dd" })
-- hi("CmpItemKindVariable", { guibg = "none", guifg = "#56b6c2" })
-- hi("CmpItemKindKeyword", { guibg = "none", guifg = "#c8ccd4" })
-- hi("DiagnosticError", { guifg = "#e06c75" })
-- hi("DiagnosticWarn", { guifg = "#d19a66" })
-- hi("DiagnosticInfo", { guifg = "#56b6c2" })
-- hi("DiagnosticHint", { guifg = "#61afef" })
-- hi("DiagnosticLineNrError", { guifg = "#e06c75" })
-- hi("DiagnosticLineNrWarn", { guifg = "#d19a66" })
-- hi("DiagnosticLineNrInfo", { guifg = "#56b6c2" })
-- hi("DiagnosticLineNrHint", { guifg = "#61afef" })
-- hi("DiagnosticSignError", { guifg = "#e06c75" })
-- hi("DiagnosticSignWarn", { guifg = "#d19a66" })
-- hi("DiagnosticSignInfo", { guifg = "#56b6c2" })
-- hi("DiagnosticSignHint", { guifg = "#61afef" })
-- hi("Normal", { guifg = "#b6bdca", guibg = "#21252b" })
-- hi("NonText", { guifg = "#b6bdca", guibg = "#21252b" })
-- hi("EndOfBuffer", { guifg = "#b6bdca", guibg = "#21252b" })
-- hi("SignColumn", { guibg = "#21252b" })
-- hi("Search", { guibg = "#e5c07b", guifg = "#282c34" })
hi("PMenu", { guifg = "#949cbb" })
-- hi("TelescopeResultsBorder", { guifg = "#abb2bf" })
-- hi("TelescopePreviewBorder", { guifg = "#abb2bf" })
-- hi("TelescopePromptBorder", { guifg = "#abb2bf" })
-- hi("TelescopeTitle", { guifg = "#abb2bf", gui = "bold" })
-- hi("TelescopeMatching", { guifg = "#61afef" })
hi("TreesitterContext", { guibg = "#363a4f" })
-- hi("TSVariable", { guifg = "#b6bdca" })
-- hi("TSField", { guifg = "#56b6c2" })
-- hi("TSParameter", { guifg = "#61afef" })
-- hi("DiffChange", { guifg = "#d19a66" })
-- hi("DiffDelete", { guifg = "#e06c75" })
-- hi("DiffAdd", { guifg = "#98c379" })
-- hi("DiffText", { guifg = "#61afef" })
-- hi("diffline", { guifg = "#61afef" })
-- hi("diffnewfile", { guifg = "#98c379" })
-- hi("difffile", { guifg = "#e06c75" })
-- hi("gitcommitsummary", { guifg = "#56b6c2" })
hi("BufferCurrentTarget", { guifg = "#e06c75" })
hi("BufferVisibleTarget", { guifg = "#e06c75" })
hi("BufferInactiveTarget", { guifg = "#e06c75", guibg = "#282c34" })
-- hi("FloatBorder", { guifg = "#6a707e", guibg = "#24273A" })
hi("NormalFloat", { guifg = "#c6d0f5" })
hi("VertSplit", { guifg = "#c6d0f5" })
-- hi("WhichKeyFloat", { guibg = "#1e2030" })
hi("NvimTreeCursorLine", { gui = "bold" })
hi("MsgArea", { guibg = "#292c3c" })
hi_link("illuminatedWordText", "LspReferenceText")
hi_link("illuminatedWordWrite", "LspReferenceText")
hi_link("illuminatedWordRead", "LspReferenceText")
